const Images = {
    header: require('../assets/icons/headeshape/headershape.png'),
    getStartedHeader: require('../assets/icons/getstartedicon/icons.png'),
    headerImage: require('../assets/icons/logoicon/icons.png'),
    leftarrow: require('../assets/icons/leftarrow/leftarrow.png'),
    hide: require('../assets/icons/passwordhidden/hide.png'),
    view: require('../assets/icons/passwordview/view.png'),
    dummyPic: require('../assets/icons/dummy/pic.png'),
    camera: require('../assets/icons/cameraicon/photo-camera.png'),
    radioSelected: require('../assets/icons/radioicon/radio.png'),
    radioUnSelected: require('../assets/icons/unselected-radio/radio.png'),
    location: require('../assets/icons/locationicon/location.png'),
    check: require('../assets/icons/remembericon/remember.png'),
    uncheck: require('../assets/icons/rememberbordericon/remember.png'),
    rightArrowButton: require('../assets/icons/nextarrow/rightarrow.png'),
    rightArrow: require('../assets/icons/rightarrowicon/arrow.png'),
    menu: require('../assets/icons/menuicon/menu.png'),
    mapIcon: require('../assets/icons/mapicon/map.png'),
    edit: require('../assets/icons/editicon/editprofile.png'),
    yellowBadge: require('../assets/icons/badge/medal.png'),
    downarrow: require('../assets/icons/downarrow/down.png'),
    addMore: require('../assets/icons/addmoreicon/add.png'),
    addPlus: require('../assets/icons/addmoreplus/Plus.png'),
    footballicon: require('../assets/icons/footballdetailicon/icon.png'),
    locationicon: require('../assets/icons/locationmarkericon/icon.png'),
    tile1: require('../assets/icons/imgs/img-1.png'),
    tile2: require('../assets/icons/imgs/img-2.png'),
    tile3: require('../assets/icons/imgs/img-3.png'),
    upload_icon: require('../assets/icons/uploadicon/upload.png'),
    protag: require('../assets/icons/proicon/protag.png'),
    fb: require('../assets/icons/socialicons/facebook.png'),
    google: require('../assets/icons/socialicons/google.png'),
    cross: require('../assets/icons/crossicon/cross.png'), 
    greycalendar: require('../assets/icons/calendaricon/calendar.png'),
    clockicon: require('../assets/icons/clockicon/clock.png'),
    online: require('../assets/icons/liveicon/Shape.png'),
    SendIcon: require('../assets/icons/sendicon/Group.png'),
    ChatPlus: require('../assets/icons/chatplusicon/plusIcon.png'),
   
    // Drawer 
    awardSelected: require('../assets/icons/sidemenu/awardicon/medal.png'),
    award: require('../assets/icons/sidemenu/awardwhite/medal.png'),
    changeSelected: require('../assets/icons/sidemenu/changepassword/lock.png'),
    change: require('../assets/icons/sidemenu/changepasswordwhite/lock.png'),
    chatSelected: require('../assets/icons/sidemenu/chaticon/comment.png'),
    chat: require('../assets/icons/sidemenu/chaticonwhite/comment.png'),
    homeSelected: require('../assets/icons/sidemenu/home/icon.png'),
    home: require('../assets/icons/sidemenu/homewhite/icon.png'),
    legalSelected: require('../assets/icons/sidemenu/legalicon/weight-balance.png'),
    legal: require('../assets/icons/sidemenu/legalwhite/weight-balance.png'),
    myEventSelected: require('../assets/icons/sidemenu/myevent/event.png'),
    myEvent: require('../assets/icons/sidemenu/myeventwhite/event.png'),
    profileSelected: require('../assets/icons/sidemenu/profile/profile.png'),
    profile: require('../assets/icons/sidemenu/profilewhite/user.png'),
    logout: require('../assets/icons/sidemenu/signouticon/logout.png'),
    supportSelected: require('../assets/icons/sidemenu/support/support.png'),
    support: require('../assets/icons/sidemenu/supportwhite/support.png'),
    verify: require('../assets/icons/verifyicon/verify.png'),
    searchicon: require('../assets/icons/searchicon/magnifying-glass.png'),
    filter : require('../assets/icons/filter/filte.png'),



   
};

export default Images