const strings ={
   name: 'First Name',
   firstName: 'Name',
   lastName: 'Last Name',
   email: 'Email',
   postal: 'Postal Code',
   password: 'Password',
   confirmPassword: 'Confirm Password',
   newPassword: 'New Password',
   signIn: 'Sign In',
   signUp: 'Sign Up',
   dob: 'Date of Birth',
   gender: 'Identity',
   select: 'Select',
   phone: 'Phone Number',
   terms: 'Terms of Use',
   privacy: 'Privacy Policy',
   termsAgree: 'I agree to the ',
   phoneVerify: 'Phone Verification',
   agreement: 'By signing up you agree with the ',
   alreadyUser: 'Already a User? ',
   signUpIntro: "Create a free account to join Gilbert's Community",
   getStarted: 'GET STARTED',
   remember: 'Remember Me',
   forgot: 'Forgot Password',
   newUser: 'New User? ',
   fillFields: 'Please fill all fields to Continue',
   validEmail: 'Please enter a valid Email to Continue',
   validPassword: 'Password should be minimum 6 characters',
   validPostal: 'Please enter valid postal code with mininum 4 characters',
   passwordMatch: 'Passwords do not match.',
   validNumber: 'Please enter a valid Phone Number',
   profile: 'Profile',
   changePassword: 'Change Password',
   saveChanges: 'Save Changes',
   support: 'Support',
   submit: 'Submit',
   resetPassword: 'Reset Password',
   termsCheck: 'Please check the box if you have read and agree to the Terms of Use and Privacy Policy.',
   location: 'Location',
   country: 'Country',
   city: 'City',
   zip: 'Zipcode',
   address: 'Address',
   about: 'About',
   about_me: 'About Me',
   sportsDetails: 'SPORTS DETAILS',
   age: 'Age',
   basicInfo: 'BASIC INFO',
   male: 'Male',
   female: 'Female',
   others: 'Other',
   favSports: 'Favorite Sports',
   sports: 'Sports',
   abilityLevel: 'Select Ability Level',
   beginner: 'Beginner',
   intermediate: 'Intermediate',
   advanced: 'Advanced',
   any: 'Any',
   datetime : 'Date & Time',
   sport : 'Sport',
   time : 'Today',
   level: 'Level',
   recur: 'How Many Times Will This Event Occur',
   price :'Price',
   featureimage : 'Event Image',
   eventname : 'EVENT NAME',
   eventlocation : 'EVENT LOCATION',
   selectsport : 'SELECT YOUR SPORT',
   max_part : 'MAXIMUM NUMBER OF PARTICIPANTS',
   recured :'NUMBER OF TIMES EVENT WOULD BE RECURRED',
   cost_event : 'COST OF THE EVENT',
   group_creation :'GROUP CREATION POLICY',
   explore : 'EXPLORE ARENA',
   find : 'FIND ATHLETE',
   view: 'VIEW EVENTS',
   create : 'CREATE EVENT',
   events : 'EVENTS',
   all : 'All',
   arena: 'ARENA',
   pro : 'PRO',
   range: 'AGE RANGE',
   validInput : 'Please enter valid data',
   moreInfo : 'MY SPORTS ABILITY',
   eventHis : 'EVENT HISTORY',
   message: 'SEND MESSAGE',
   emailphone: 'Email',
   join: 'REQUEST TO JOIN',
   requested: 'REQUESTED',
   update : 'UPDATE EVENT',
   created: 'Created By:',
   eligible:'ELIGIBLE PARTICIPANTS',
   individual: 'Individual',
   company: 'Company',
   sport_cat : 'SPORTS CATEGORY',
   apply : 'APPLY',
   Gendr : 'GENDER',
   ViewParticipant : 'VIEW PARTICIPANTS',
   ABOUT_ME : 'ABOUT ME',
   FavSprt : 'FAVORITE SPORTS',
   MoreAbility : 'MORE ABILITY INFO',
   Accept : 'ACCEPT',
   Reject : 'Reject'

};

export default strings