const types = {
    GET_LOGIN: 'GET_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    GET_PROFILE: 'GET_PROFILE',
    PROFILE_SUCCESS: 'PROFILE_SUCCESS',
    PROFILE_FAILURE: 'PROFILE_FAILURE',
    CHANGE_PASS_SUCCESS: 'CHANGE_PASS_SUCCESS',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_STATUS : 'UPDATE_STATUS',
    UPDATE_SUCCESS : 'UPDATE_SUCCESS',
    UPDATE_FAIL : 'UPDATE_FAIL',


    GET_CATEGORIES: 'GET_CATEGORIES',
    CATEGORIES_SUCCESS: 'CATEGORIES_SUCCESS',
    CATEGORIES_FAILURE: 'CATEGORIES_FAILURE',
    GET_MYEVENYTS : 'GET_MYEVENYTS',
    EVENTS_FAILURE: 'EVENTS_FAILURE',
    GET_MYEVENYTS_SUCCESS: 'GET_MYEVENYTS_SUCCESS',
    CREATE_EVENT_START : 'CREATE_EVENT_START',
    CREATE_EVENT_START_SUCCESS :'CREATE_EVENT_START_SUCCESS',
    CREATE_EVENT_FAILURE : 'CREATE_EVENT_FAILURE',

    UPDATE_EVENT_START:'UPDATE_EVENT',
    UPDATE_EVENT_SUCCESS:'UPDATE_EVENT_SUCCESS',
    UPDATE_EVENT_FAILURE:'UPDATE_EVENT_FAILURE',


    FINDATHLETE_START : 'FINDATHLETE_START',
    ATHLETE_SUCCESS: 'ATHLETE_SUCCESS',
    ATHLETE_FAILURE: 'ATHLETE_FAILURE',
    ALLEVENT_START: 'ALLEVENT_START',
    ALLEVENT_SUCCESS: 'ALLEVENT_SUCCESS',
    ALLEVENT_FAILURE: 'ALLEVENT_FAILURE',

    REGISTER_START: 'REGISTER_START',
    LOGIN_START: 'LOGIN_START',
    SOCIAL_LOGIN_START: 'SOCIAL_LOGIN_START',
    FORGOT_START: 'FORGOT_START',
    OTP_START: 'OTP_START',
    RESET_START: 'RESET_START',
    CHANGE_PASS: 'CHANGE_PASS',
    LOGOUT : 'LOGOUT',

    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',
    SET_USER: 'SET_USER'
}

export default types